name: Reviewdog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@64c149605d92715a545b1d80908eff8cecec21b1 # v2.7.1
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          reporter: github-pr-review
